### ISSUE TITLE
No such file or directory: '/home/aaa/Documents/MFA/Librispeech/models/HCLGa.temp'

### ISSUE THREAD

**Issue by 980202006** [MontrealCorpusTools/Montreal-Forced-Aligner#319] opened 2021-08-09 08:48 UTC
when I run mfa transcribe,there is an error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/aaa/Documents/MFA/Librispeech/models/HCLGa.temp'

when run    os.remove(temp_compose_path)

Is there  an example for how to run mfa transcribe

**Comment by mmcauliffe** [comment] 2021-10-02 19:06
This should be resolved in the latest release, duplicate of #327

**Closed by mmcauliffe** 2021-10-02 19:06 UTC
