### ISSUE TITLE
[BUG] Export speed is extramely slow when collecting phone and word alignments from alignment lattices

### ISSUE THREAD

**Issue by Approximetal** [MontrealCorpusTools/Montreal-Forced-Aligner#447] opened 2022-05-10 06:59 UTC
**Debugging checklist**

[ √ ] Have you updated to latest MFA version?
[ √ ] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
When I generate alignments using a acoustic model trained from scratch, the speed would be extramely slow at the last step. Please see the picture below.

**For Reproducing your issue**
Example: 
 1. mfa train -t ./temp -j 16 ./aligner/wavs_aligner vietnamese_hanoi_mfa ./vietnamese_acoustic.zip --clean
 2. mfa align -t ./temp -j 16 aligner/wavs_aligner vietnamese_hanoi_mfa vietnamese_acoustic.zip ./aligner/aligned --debug --clean

1. Corpus structure
   * What language is the corpus in? 
      I have tried Mandarin (baker dataset) and Vietnamese (ReInfo dataset), both have such issue.
   * How many files/speakers?
      Single speaker TTS dataset.
   * Are you using lab files or TextGrid files for input?
      text file

2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * It is the provided 2.0 dictionaries on your website.

3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one?
     I couldn't use the 1.0 vietnamese pretrained model to generate alignments, because it occoured errors like this, and I don't know which symbol is symbol 895. 
 `ERROR (compile-train-graphs[5.5.992]:TrainingGraphCompiler():decoder/training-graph-compiler.cc:43) Disambiguation symbol 895 is also a phone.
kaldi::KaldiFatalError`

   * If it's a model you've trained, what data was it trained on?
    [InfoRe Technology 1](https://github.com/TensorSpeech/TensorFlowASR/blob/main/README.md#vietnamese) 

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Ubuntu 20.04
 - Any other details about the setup (Cloud, Docker, etc) conda 

**Additional context**
![image](https://user-images.githubusercontent.com/25227045/167564596-fcdc2dd6-765d-47ad-93b4-5f61b9a6b50a.png)

**Comment by mmcauliffe** [comment] 2022-05-18 03:52
Was it still running but slowly?  Or did it error out after a few returned results?  MFA isn't well optimized at the moment for single speaker cases with lots of files, but it still shouldn't take that long to export even just using a single core.  You could try doing some arbitrary splits of the data as pseudo-speakers and that'll make it faster.  In the meantime, I'll check out the data you linked and see if I can reproduce the issue.

**Comment by Approximetal** [comment] 2022-06-07 07:02
Yes, it works well now in v2.0.0rc9. Thank you for your help!
Also I couldn't find the 1.0 version pretrained models and dictionaries, and failed to open the links of the 1.0 version document. I'd love to know why you chose to hide those previous resources as I think they are very useful.

**Comment by mmcauliffe** [comment] 2022-06-08 17:56
Right they're a little buried at the moment, you can see all the acoustic models here: https://github.com/MontrealCorpusTools/mfa-models/releases/tag/acoustic-archive-v1.0, but the primary issue with many of the 1.0 dictionaries was that we can't actually distribute them under the global phone license. We trained [G2P models](https://github.com/MontrealCorpusTools/mfa-models/releases/tag/g2p-archive-1.0) to get around that a little bit but in general 1.0 models based on Global Phone lexicon are not as good as the recent ones I've been working on. I've put together some simple benchmarks for [Korean alignments](https://mfa-models.readthedocs.io/en/latest/benchmarks/korean_alignments.html) and [Global Phone transcription](https://mfa-models.readthedocs.io/en/latest/benchmarks/globalphone_transcriptions.html). 

That said, I'll update the links in the 1.0 docs to point to the updated location.

**Comment by mmcauliffe** [comment] 2022-06-10 19:03
Going to close this out now, since the original issue is fixed, and I've updated the 1.0 docs to point to the correct files now.

**Closed by mmcauliffe** 2022-06-10 19:03 UTC
Labels: bug
