### ISSUE TITLE
KeyError: 'EY0_E' running 'mfa train'

### ISSUE THREAD

**Issue by matpalm** [MontrealCorpusTools/Montreal-Forced-Aligner#292] opened 2021-06-01 06:43 UTC
Hello `mfa` people!

I'm attempting to run forced alignment against the [common voice dataset](https://commonvoice.mozilla.org/en/datasets)

I've prepared some data and things are fine when I run an alignment using a trained acoustic model;
e.g. something like 

```
mfa align --clean --temp_directory /data/tmp/mfa/ --num_jobs 8 --verbose \
 /data2/cv_corpus/sample librispeech-lexicon.txt english \
 /data4/cv_alignments/sample/
```

But given the dataset size it's going to take too long for me; so I thought I'd try to just use the mode without an acoustic model, which, if I understand correctly, is something like ...

```
mfa train --debug /data2/cv_corpus/sample/ librispeech-lexicon.txt /tmp/test
```

The trouble is that fails with a key error I don't understand :(

```
All required kaldi binaries were found!
/home/mat/Documents/MFA/sample/train_and_align.log
WARNING - Running in DEBUG mode, may have impact on performance and disk usage.
WARNING - WARNING: Using old temp directory, this might not be ideal for you, use the --clean flag to ensure no weird behavior for previous versions of the temporary directory.
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 28, average number of utterances per speaker: 3.5357142857142856
INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
INFO - Creating dictionary information...
Traceback (most recent call last):
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/bin/mfa", line 8, in <module>
    sys.exit(main())
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 349, in main
    run_train_corpus(args, unknown)
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 153, in run_train_corpus
    align_corpus(args, unknown_args)
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_and_align.py", line 100, in align_corpus
    a = TrainableAligner(corpus, dictionary, train_config, align_config,
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 32, in __init__
    super(TrainableAligner, self).__init__(corpus, dictionary, align_config, temp_directory,
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/base.py", line 58, in __init__
    self.setup()
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/aligner/trainable.py", line 38, in setup
    self.dictionary.write()
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/dictionary.py", line 550, in write
    self._write_align_lexicon()
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/dictionary.py", line 656, in _write_align_lexicon
    p = ' '.join(str(self.phone_mapping[x]) for x in phones)
  File "/home/mat/dev/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/dictionary.py", line 656, in <genexpr>
    p = ' '.join(str(self.phone_mapping[x]) for x in phones)
KeyError: 'EY0_E'
```

I'm wondering if this is I problem with how I'm started `mfa train`? Or something with the `librispeech-lexicon.txt` (which I downloaded from http://www.openslr.org/resources/11/librispeech-lexicon.txt )

Any help much appreciated, it's an awesome tool!
Cheers, Mat

**Comment by ada-k** [comment] 2021-06-17 05:05
did you ever resolve this?
I'm getting a somewhat similar traceback but with `KeyError: 'AA0_B'` instead.

**Comment by matpalm** [comment] 2021-06-17 05:11
i haven't yet; but advice i got from someone else, that i haven't tried yet, is...

```
From the github issue, are you using a static lexicon file on Common Voice data? 
Maybe that's the issue - if I understand correctly, you have to generate the lexicon
file from the Common Voice transcripts. It's in the format
word w o r d
for each unique word in the .lab transcripts. 

My jupyter cell for generating a lexicon file is here: 
https://github.com/harvard-edge/multilingual_kws/blob/main/alignment/reorganize_luganda.py#L66-L91 
```

**Comment by ada-k** [comment] 2021-06-17 05:21
Thanks. I'm gonna try that. 'll let you know if it works on my end.

**Comment by mmcauliffe** [comment] 2021-06-17 06:19
Thanks for bumping this, I'll download the corpus this week and see what's going on this weekend.

**Comment by ada-k** [comment] 2021-06-17 06:48
> Thanks. I'm gonna try that. 'll let you know if it works on my end.

It worked, got past the bug. It's now training.

**Comment by mmcauliffe** [comment] 2021-06-27 20:31
I wasn't able to replicate this, my guess is that it's caused by the difference between the align run and the train run and `--clean` would likely resolve it.  It sounds like you've got something that's working, so I'm going to close this.

**Closed by mmcauliffe** 2021-06-27 20:31 UTC

**Comment by nrgslp** [comment] 2021-07-03 01:28
I've just run into this same issue (but with the biphone `ER2_I`). I'm using a dictionary that I've used successfully before. @ada-k , what did you do to get past this bug?

**Comment by ada-k** [comment] 2021-07-04 11:39
I had to generate a new lexicon file from the common voice transcripts using the [link](https://github.com/harvard-edge/multilingual_kws/blob/main/alignment/reorganize_luganda.py#L66-L91) that @matpalm shared.

**Comment by nrgslp** [comment] 2021-07-04 11:46
Right, but what did this change about the content of your dict file vs what you had first passed to `mfa train`?

**Comment by ada-k** [comment] 2021-07-05 13:25
I had to run `mfa validate ...`  to see if the *issues message* could guide me in understanding the difference between the 2 dicts, and what I picked from it is that one file had some words missing and the other captured everything. 
I'm not sure how much specificity you need here but from my understanding -- regenerating the dict file using your wavs makes the  dict more tailored.

**Comment by nrgslp** [comment] 2021-07-06 12:35
Okay, I didn't realize that you were not using a custom dict file at the start. I think I can take from this that there is something wrong in my custom dict file, but what perplexes me is that I've aligned with this dict before.

As a side note - the solution that worked for you seems to create a dict in the format `WORD w o r d`, i.e., spelling and not phones (`WORD W ER1 D`)? Wouldn't that result in noisy models and alignments?

**Comment by nrgslp** [comment] 2021-07-07 02:50
Update for those who land here later - I got past this error using a fresh version of CMU_SPHINX (Librispeech did not work for me).

**Comment by ada-k** [comment] 2021-07-11 18:51
> Okay, I didn't realize that you were not using a custom dict file at the start. I think I can take from this that there is something wrong in my custom dict file, but what perplexes me is that I've aligned with this dict before.
> 
> As a side note - the solution that worked for you seems to create a dict in the format `WORD w o r d`, i.e., spelling and not phones (`WORD W ER1 D`)? Wouldn't that result in noisy models and alignments?

this is a very strong point & a very helpful pointer, thanks for bringing it up. Looks like I need to go over the process again.

**Comment by mmcauliffe** [comment] 2021-07-17 00:16
Thanks to @tshmak for pointing out a potential cause of this, @nrgslp could you try updating to the latest version and trying out the case that didn't work for you to see if the fix works?

**Comment by nrgslp** [comment] 2021-09-08 00:20
@mmcauliffe I do believe updating has fixed things for me. Thanks!
