### ISSUE TITLE
ZeroDivisionError: division by zero error in montreal_forced_aligner/alignment/base.py", line 273, in compute_pronunciation_probabilities

### ISSUE THREAD

**Issue by DanojaDias** [MontrealCorpusTools/Montreal-Forced-Aligner#443] opened 2022-05-03 08:12 UTC
Hi All, 

I am going through the steps in the documentation.

https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/index.html#first-steps-align-train-acoustic-model.

I did the `mfa validate` command successfully and following is the output I got.

> INFO - ******
> INFO - Corpus
> INFO - ******
> 
> INFO -   3300 sound files
> INFO -   3300 text files
> INFO -   1 speakers
> INFO -   3300 utterances
> INFO -   27678.299 seconds total duration
> 
> INFO -   Sound file read errors
> INFO -   ======================
> 
> INFO -     There were no issues reading sound files.
> 
> INFO -   Feature generation
> INFO -   ==================
> 
> INFO -     There were no utterances missing features.
> 
> INFO -   Files without transcriptions
> INFO -   ============================
> 
> INFO -     There were no sound files missing transcriptions.
> 
> INFO -   Transcriptions without sound files
> INFO -   ==================================
> 
> INFO -     There were no transcription files missing sound files.
> 
> 
> INFO - **********
> INFO - Dictionary
> INFO - **********
> 
> INFO -   Out of vocabulary words
> INFO -   =======================
> 
> INFO -     80 OOV word types
> INFO -     64681 total OOV tokens
> 
> INFO -     For a full list of the word types, please see:
> 
> INFO -         /root/Documents/MFA/_validate_training/oovs_found.txt
> 
> INFO -     For a by-utterance breakdown of missing words, see:
> 
> INFO -         /root/Documents/MFA/_validate_training/utterance_oovs.txt

Then when trying the command `mfa train` I get a ZeroDivisionError. StackTrace is as below.

> INFO - Generating pronunciations...
>   0% 0/3300 [00:02<?, ?it/s]
> ERROR - There was an error in the run, please see the log.
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/tmp/mfa/miniconda3/envs/aligner/bin/mfa", line 8, in <module>
>     sys.exit(main())
>   File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 986, in main
>     run_train_acoustic_model(args, unknown)
>   File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 108, in run_train_acoustic_model
>     train_acoustic_model(args, unknown_args)
>   File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/train_acoustic_model.py", line 36, in train_acoustic_model
>     trainer.train()
>   File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/acoustic_modeling/trainer.py", line 358, in train
>     trainer.train_pronunciation_probabilities()
>   File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/acoustic_modeling/pronunciation_probabilities.py", line 153, in train_pronunciation_probabilities
>     self.worker.compute_pronunciation_probabilities(self.silence_probabilities)
>   File "/tmp/mfa/miniconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/alignment/base.py", line 273, in compute_pronunciation_probabilities
>     silence_probability = silence_count / (silence_count + non_silence_count)
> ZeroDivisionError: division by zero

pronunciation_probability_calculation.log file has the all counts as zero like this.

> For 1:
> Total silence count was 0
> Total non silence count was 0

How can I solve this issue ?

**Comment by mmcauliffe** [comment] 2022-05-04 00:22
Hmm, that's weird. Can you check the `generate_pronunciations.X.log` files and see if they're generating correctly?  They should have lines like:

```
987-115633	[('<eps>', 'sil'), ('quotations', 'K W OW0 T EY1 SH AH0 N Z'), ('<eps>', 'sil'), ('on', 'AA1 N'), ('the', 'DH AH0'), ('flyleaf', 'F L AY1 L IY2 F'), ('<eps>', 'sil'), ('where', 'HH W EH1 R'), ('the', 'DH AH0'), ("queen's", 'K W IY1 N Z'), ('law', 'L AO1'), ('<eps>', 'sil'), ('does', 'D AH1 Z'), ('<eps>', 'sil'), ('not', 'N AA1 T'), ('<eps>', 'sil'), ('carry', 'K EH1 R IY0'), ('<eps>', 'sil')]
```

I have some changes that fix a different bug in silence calculation that I should get out tonight, but this sounds like the pronunciation counters are just empty for some reason.

**Comment by DanojaDias** [comment] 2022-05-04 09:25
`generate_pronunciations.X.log` file is not generated correctly. This file is empty. Nothing in this file.

**Comment by DanojaDias** [comment] 2022-05-05 05:57
@mmcauliffe What could be the reason for being generate_pronunciations.X.log is empty ? Could it be the problem with my corpus and dictionary. But `mfa validate` is successful. Could you please help me with this ?

**Comment by mmcauliffe** [comment] 2022-05-05 19:54
Version 2.0.0rc7 is out, with some fixes around pronunciation probability training, can you try upgrading to it and rerunning with `--clean`?

**Comment by Chenzk** [comment] 2022-06-01 03:53
@DanojaDias -- did you solve this problem?

**Comment by mmcauliffe** [comment] 2022-06-10 19:05
I'm going to close this out for now, not sure if I'll be able to replicate it on google colab if that's the root cause, but feel free to open a separate issue for anything that's going wrong specifically on colab if it's blocking you.

**Closed by mmcauliffe** 2022-06-10 19:05 UTC
